export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST"
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS"
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL"
export const USER_LOGOUT = "USER_LOGOUT"

export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST"
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS"
export const USER_REGISTER_FAIL = "USER_REGISTER_FAIL"

export const USER_ACTIVATE_REQUEST = "USER_ACTIVATE_REQUEST"
export const USER_ACTIVATE_SUCCESS = "USER_ACTIVATE_SUCCESS"
export const USER_ACTIVATE_FAIL = "USER_ACTIVATE_FAIL"

export const USER_RESET_PASSWORD_REQUEST = "USER_RESET_PASSWORD_REQUEST"
export const USER_RESET_PASSWORD_SUCCESS = "USER_RESET_PASSWORD_SUCCESS"
export const USER_RESET_PASSWORD_FAIL = "USER_RESET_PASSWORD_FAIL"

export const USER_RESET_PASSWORD_CONFIRM_REQUEST = "USER_RESET_PASSWORD_CONFIRM_REQUEST"
export const USER_RESET_PASSWORD_CONFIRM_SUCCESS = "USER_RESET_PASSWORD_CONFIRM_SUCCESS"
export const USER_RESET_PASSWORD_CONFIRM_FAIL = "USER_RESET_PASSWORD_CONFIRM_FAIL"

export const POST_INDEX_REQUEST = "POST_INDEX_REQUEST"
export const POST_INDEX_SUCCESS = "POST_INDEX_SUCCESS"
export const POST_INDEX_FAIL = "POST_INDEX_FAIL"

export const GET_USERS_REQUEST = 'GET_USERS_REQUEST'
export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS'
export const GET_USERS_FAIL = 'GET_USERS_FAIL'



export const GET_PROFILE_REQUEST = "GET_PROFILE_REQUEST";
export const GET_PROFILE_SUCCESS = "GET_PROFILE_SUCCESS";
export const GET_PROFILE_FAIL = "GET_PROFILE_FAIL";

export const GET_USER_PROFILE_REQUEST = "GET_USER_PROFILE_REQUEST";
export const GET_USER_PROFILE_SUCCESS = "GET_USER_PROFILE_SUCCESS";
export const GET_USER_PROFILE_FAIL = "GET_USER_PROFILE_FAIL";

export const UPDATE_PROFILE_REQUEST = "UPDATE_PROFILE_REQUEST";
export const UPDATE_PROFILE_SUCCESS = "UPDATE_PROFILE_SUCCESS";
export const UPDATE_PROFILE_FAIL = "UPDATE_PROFILE_FAIL";

export const LIST_AGENTS_REQUEST = "LIST_AGENTS_REQUEST";
export const LIST_AGENTS_SUCCESS = "LIST_AGENTS_SUCCESS";
export const LIST_AGENTS_FAIL = "LIST_AGENTS_FAIL";

export const LIST_TOP_AGENTS_REQUEST = "LIST_TOP_AGENTS_REQUEST";
export const LIST_TOP_AGENTS_SUCCESS = "LIST_TOP_AGENTS_SUCCESS";
export const LIST_TOP_AGENTS_FAIL = "LIST_TOP_AGENTS_FAIL";

export const LIST_ALL_USERS_PROFILE_REQUEST = "LIST_ALL_USERS_PROFILE_REQUEST"
export const LIST_ALL_USERS_PROFILE_SUCCESS = "LIST_ALL_USERS_PROFILE_SUCCESS"
export const LIST_ALL_USERS_PROFILE_FAIL = "LIST_ALL_USERS_PROFILE_FAIL"

export const LIST_ALL_POSTS_REQUEST = "LIST_ALL_POSTS_REQUEST";
export const LIST_ALL_POSTS_SUCCESS = "LIST_ALL_POSTS_SUCCESS";
export const LIST_ALL_POSTS_FAIL = "LIST_ALL_POSTS_FAIL";

export const LIST_AGENTS_PROPERTIES_REQUEST = "LIST_AGENTS_PROPERTIES_REQUEST";
export const LIST_AGENTS_PROPERTIES_SUCCESS = "LIST_AGENTS_PROPERTIES_SUCCESS";
export const LIST_AGENTS_PROPERTIES_FAIL = "LIST_AGENTS_PROPERTIES_FAIL";

export const CREATE_POST_REQUEST = "CREATE_POST_REQUEST";
export const CREATE_POST_SUCCESS = "CREATE_PROPERTY_SUCCESS";
export const CREATE_POST_FAIL = "CREATE_POST_FAIL";

export const UPDATE_POST_REQUEST = "UPDATE_POST_REQUEST";
export const UPDATE_POST_SUCCESS = "UPDATE_POST_SUCCESS";
export const UPDATE_POST_FAIL = "UPDATE_POST_FAIL";

export const DELETE_POST_REQUEST = "DELETE_POST_REQUEST";
export const DELETE_POST_SUCCESS = "DELETE_POST_SUCCESS";
export const DELETE_POST_FAIL = "DELETE_POST_FAIL";

export const POST_DETAILS_REQUEST = "POST_DETAILS_REQUEST";
export const POST_DETAILS_SUCCESS = "POST_DETAILS_SUCCESS";
export const POST_DETAILS_FAIL = "POST_DETAILS_FAIL";

export const SEARCH_POST_REQUEST = "SEARCH_POST_REQUEST";
export const SEARCH_POST_SUCCESS = "SEARCH_POST_SUCCESS";
export const SEARCH_POST_FAIL = "SEARCH_POST_FAIL";

export const UPLOAD_POST_IMAGE_REQUEST = "UPLOAD_POST_IMAGE_REQUEST";
export const UPLOAD_POST_IMAGE_SUCCESS = "UPLOAD_POST_IMAGE_SUCCESS";
export const UPLOAD_POST_IMAGE_FAIL = "UPLOAD_POST_IMAGE_FAIL";

export const CART_ADD_ITEM_REQUEST = "CART_ADD_ITEM_REQUEST"
export const CART_ADD_ITEM_SUCCESS = "CART_ADD_ITEM_SUCCESS"
export const CART_ADD_ITEM_FAIL = "CART_ADD_ITEM_FAIL"

export const CART_REMOVE_ITEM_REQUEST = "CART_REMOVE_ITEM_REQUEST"
export const CART_REMOVE_ITEM_SUCCESS = "CART_REMOVE_ITEM_SUCCESS"
export const CART_REMOVE_ITEM_FAIL = "CART_REMOVE_ITEM_FAIL"

export const CART_CLEAR_REQUEST = "CART_CLEAR_REQUEST"
export const CART_CLEAR_SUCCESS = "CART_CLEAR_SUCCESS"
export const CART_CLEAR_FAIL = "CART_CLEAR_FAIL"

export const CART_FETCH_REQUEST = "CART_FETCH_REQUEST"
export const CART_FETCH_SUCCESS = "CART_FETCH_SUCCESS"
export const CART_FETCH_FAIL = "CART_FETCH_FAIL"

export const GET_ALL_ORDERS_REQUEST = "GET_ALL_ORDERS_REQUEST"
export const GET_ALL_ORDERS_SUCCESS = "GET_ALL_ORDERS_SUCCESS"
export const GET_ALL_ORDERS_FAIL = "GET_ALL_ORDERS_FAIL"

export const INITIATE_PAYMENT_REQUEST = 'INITIATE_PAYMENT_REQUEST';
export const INITIATE_PAYMENT_SUCCESS = 'INITIATE_PAYMENT_SUCCESS';
export const INITIATE_PAYMENT_FAIL = 'INITIATE_PAYMENT_FAIL';

export const VERIFY_PAYMENT_REQUEST = 'VERIFY_PAYMENT_REQUEST';
export const VERIFY_PAYMENT_SUCCESS = 'VERIFY_PAYMENT_SUCCESS';
export const VERIFY_PAYMENT_FAIL = 'VERIFY_PAYMENT_FAIL';

export const POST_COMMENT_CREATE_REQUEST = 'POST_COMMENT_CREATE_REQUEST';
export const POST_COMMENT_CREATE_SUCCESS = 'POST_COMMENT_CREATE_SUCCESS';
export const POST_COMMENT_CREATE_FAIL = 'POST_COMMENT_CREATE_FAIL';

export const POST_COMMENT_UPDATE_REQUEST = 'POST_COMMENT_UPDATE_REQUEST';
export const POST_COMMENT_UPDATE_SUCCESS = 'POST_COMMENT_UPDATE_SUCCESS';
export const POST_COMMENT_UPDATE_FAIL = 'POST_COMMENT_UPDATE_FAIL';

export const POST_COMMENT_DELETE_REQUEST = 'POST_COMMENT_DELETE_REQUEST';
export const POST_COMMENT_DELETE_SUCCESS = 'POST_COMMENT_DELETE_SUCCESS';
export const POST_COMMENT_DELETE_FAIL = 'POST_COMMENT_DELETE_FAIL';

export const POST_COMMENT_LIST_REQUEST = 'POST_COMMENT_LIST_REQUEST';
export const POST_COMMENT_LIST_SUCCESS = 'POST_COMMENT_LIST_SUCCESS';
export const POST_COMMENT_LIST_FAIL = 'POST_COMMENT_LIST_FAIL';